apiVersion: apps/v1
kind: Deployment
metadata:
  name: legitimate-pool
  namespace: poison-attack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: legitimate-pool
  template:
    metadata:
      labels:
        app: legitimate-pool
    spec:
      containers:
      - name: legitimate-worker
        image: poison-legitimate:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: NUM_USERS
          value: "67"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
